# Generated by Django 4.1 on 2022-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4)),
                ('doorStatus', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=1)),
                ('floor', models.IntegerField()),
                ('motion', models.CharField(choices=[('M', 'Moving'), ('S', 'Stopped')], max_length=1)),
                ('operational', models.BooleanField(default=True)),
            ],
        ),
    ]
