# Generated by Django 3.2.5 on 2022-08-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='direction',
        ),
        migrations.AddField(
            model_name='elevator',
            name='listofRequest',
            field=models.TextField(default=''),
        ),
    ]
