# Generated by Django 3.2.5 on 2022-08-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_alter_elevator_listofrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='floor',
            new_name='currentFloor',
        ),
    ]
