# Generated by Django 3.2.5 on 2022-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_rename_floor_elevator_currentfloor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='doorStatus',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6),
        ),
    ]
