# Generated by Django 3.2.5 on 2022-08-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_alter_elevator_doorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='motion',
            field=models.CharField(choices=[('Moving', 'Moving'), ('Stopped', 'Stopped')], max_length=7),
        ),
    ]
