# Generated by Django 3.2.5 on 2022-08-24 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_alter_elevator_motion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='listofRequest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=list, null=True), blank=True, null=True, size=None),
        ),
    ]
